# -*- coding: utf-8 -*-
"""Aula08.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EALqgthhvAOv0omiUpMpsy27wawuueUP
"""

import random
def popular_lista(lista, quantidade):
  for i in range(quantidade):
    lista.append(random.randint(1, 100))

def exibir_lista(lista):
  for item in lista:
    print(item)
def copiar_numeros(lista_numeros, lista_pares, lista_impares):
  for numero in lista_numeros:
    if numero % 2 == 0:
      lista_pares.append(numero)
    else:
      lista_impares.append(numero)

lista_numeros_aleatorios = []
lista_pares = []
lista_impares = []

popular_lista(lista_numeros_aleatorios, 10)
exibir_lista(lista_numeros_aleatorios)

copiar_numeros(lista_numeros_aleatorios, lista_pares, lista_impares)
print("pares:")
exibir_lista(lista_pares)
print("impares:")
exibir_lista(lista_impares)