# -*- coding: utf-8 -*-
"""aula07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aSf7ALI0IX63eA1NRi4_U6_CTzlXntir
"""

#list comprehension
import random
numeros = [1, 2, 3, 4, 5, 6, 7, 8]
pares = [n for n in numeros if n % 2 == 0]
impares = [n for n in numeros if n % 2 != 0]

print(pares)
print(impares)

lista_numeros = []
lista_nomes = []

lista_numeros.append(5)
lista_numeros.append(3)
lista_numeros.append(1)
print(lista_numeros)

lista_nomes.append("João")
lista_nomes.append("Maria")
lista_nomes.append("Pedro")

for i in range(5):
  numero_sorteado = random.randint(0,100)
  lista_numeros.append(numero_sorteado)
print(lista_numeros)

lista_numeros.sort()
print(lista_numeros)

numero_pesquisa = int(input("Digite um número para pesquisar: "))
if numero_pesquisa in lista_numeros:
  print("O número", numero_pesquisa, "está na lista.")
else:
  print("O número", numero_pesquisa, "não está na lista.")

if(numero_pesquisa in lista_numeros):
  lista_numeros.remove(numero_pesquisa)
else:
  print("O número", numero_pesquisa, "não está na lista.")

#media, maior, menor
lista_numeros = []
for i in range(5):
  numero_sorteado = random.randint(0,100)
  lista_numeros.append(numero_sorteado)

lista_numeros.sort()
print(lista_numeros)
media = sum(lista_numeros) / len(lista_numeros)
print("A média dos números é:", media)
maior = max(lista_numeros)
print("O maior número é:", maior)
menor = min(lista_numeros)
print("O menor número é:", menor)

#mediana
lista_numeros = []
for i in range(5):
  numero_sorteado = random.randint(0,100)
  lista_numeros.append(numero_sorteado)

lista_numeros.sort()
print(lista_numeros)
mediana = lista_numeros[(len(lista_numeros)//2)]
print("A mediana dos números é:", mediana)

#apagar todos os valores pares
lista_numeros = []
for i in range(5):
  numero_sorteado = random.randint(0,100)
  lista_numeros.append(numero_sorteado)

lista_numeros.sort()
print(lista_numeros)
lista_numeros = [n for n in lista_numeros if n % 2 != 0]
print(lista_numeros)

lista_numeros = []
for i in range(50):
  numero_sorteado = random.randint(0,100)
  lista_numeros.append(numero_sorteado)

lista_numeros.sort()
print(lista_numeros)
repetidos = []
for n in lista_numeros:
  if lista_numeros.count(n) > 1:
    repetidos.append(n)
print(repetidos)
lista_numeros = [n for n in lista_numeros if n not in repetidos]
print(lista_numeros)