# -*- coding: utf-8 -*-
"""Aula08b.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17NRPaTKz5uLd1MTfyBKaWLhYCY6xAwWT
"""

import random
def sortear_valores_inflacao(lista, quantidade):
  for i in range(quantidade):
    lista.append(random.randint(4, 10))
def exibir_dados_inflacao(lista):
  for item in lista:
    print(item)
def calcular_min(lista):
  menor = lista[0]
  mes = 0
  for i in range(len(lista)):
    if lista[i] < menor:
      menor = lista[i]
      mes = i
  return menor, mes + 1
def calcular_max(lista):
  maior = lista[0]
  mes = 0
  for i in range(len(lista)):
    if lista[i] > maior:
      maior = lista[i]
      mes = i
  return maior, mes + 1

lista_inflacao = []

sortear_valores_inflacao(lista_inflacao, 12)
exibir_dados_inflacao(lista_inflacao)

lista_meses = ['',"janeiro", "fevereiro", "março", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro"]
valor_minimo, mes_minimo = calcular_min(lista_inflacao)

valor_maximo, mes_maximo = calcular_max(lista_inflacao)

print(f"valor mínimo: {valor_minimo}")
print(f"mês mínimo: {lista_meses[mes_minimo]}")

print(f"valor máximo: {valor_maximo}")
print(f"mês máximo: {lista_meses[mes_maximo]}")