# -*- coding: utf-8 -*-
"""aula10-AtividadeAvaliativa02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rZi2wx52CV-bSsh1PyQFSL9DgEqUFnBd
"""

def ler_arquivo(nome_arquivo):
    jogadores = []
    with open(nome_arquivo, 'r', encoding='utf-8') as arquivo:
        for linha in arquivo:
            dados = linha.strip().split(";")

            jogador = {
                "nome": dados[0],
                "classe": dados[1],
                "kills": int(dados[2]),
                "deaths": int(dados[3]),
                "dano": int(dados[4])
            }
            jogadores.append(jogador)

    return jogadores

def calcular_kda(kills, deaths):
    if deaths == 0:
        return float(kills)

    return kills / deaths

def filtrar_classe(lista_jogadores, classe):
    jogadores_classe = []

    for jogador in lista_jogadores:
        if jogador["classe"] == classe:
            jogadores_classe.append(jogador)

    return jogadores_classe

def exibir_destaques(lista_jogadores):
    maior_dano = 0
    nome_jogador = ""
    soma_kills = 0

    for jogador in lista_jogadores:
        if jogador["dano"] > maior_dano:
            maior_dano = jogador["dano"]
            nome_jogador = jogador["nome"].upper()

        soma_kills += jogador["kills"]

    print(f" JOGADOR COM MAIOR DANO: {nome_jogador} -> CAUSOU {maior_dano} DE DANO NO TOTAL!")

    media_kills = soma_kills / len(lista_jogadores)
    print(f" A MÉDIA DE KILLS DA PARTIDA FOI: {media_kills:.2f}")

    print("\n LISTA DE JOGADORES COM KDA SUPERIOR A 2.0:")
    for jogador in lista_jogadores:
        kda = calcular_kda(jogador["kills"], jogador["deaths"])

        if kda > 2.0:
            print(f"-> {jogador['nome'].upper()} (KDA: {kda:.2f})")

def principal():
    nome_arquivo = "/content/partida.txt"
    dados = ler_arquivo(nome_arquivo)

    tipo = input('Digite o tipo de classe que você gostaria de filtrar: ')
    tipo = tipo.capitalize()

    classe = filtrar_classe(dados, tipo)
    print(f"Jogadores da classe "+tipo+":")
    for i in classe:
        print(i.get("nome"))
    print("\n")

    print(f"DESTAQUES DA PARTIDA:")
    exibir_destaques(dados)

if __name__ == "__main__":
    principal()